version: "3.3"
   
services:
  backend:
    container_name: backend
    build:
      context: ./api
      dockerfile: Dockerfile
    #command: daphne -b 0.0.0.0 -p 8000 backend.asgi:application
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./api:/home/app/api
    ports:
      - "8000:8000"
      - "8001:8001/udp"
      - "1235:1235/udp"
    depends_on:
      - redis

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: yarn start
    #command: tail -f /dev/null
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes: 
      - ./frontend:/home/app/frontend
      - /home/app/frontend/node_modules/
    ports:
      - "3000:3000"
    depends_on:
      - backend

  redis:
    image: "redis:alpine"
    #command: redis-server --requirepass sOmE_sEcUrE_pAsS
    ports:
      - "6379:6379"
    # add config later

  #cfs:
  #  container_name: cfs
  #  command: tail -f /dev/null
  #  build:
  #    context: ./cfs
  #    dockerfile: Dockerfile

  
